####################################################################
#   Crowsnest Camera Configuration
####################################################################
#
#   Port 8080 = /webcam/?action=[stream/snapshot]
#   Port 8081 = /webcam2/?action=[stream/snapshot]
#   Port 8082 = /webcam3/?action=[stream/snapshot]
#   Port 8083 = /webcam4/?action=[stream/snapshot]
#
#   RTSP: rtsp://<ip>:<rtsp_port>/stream.h264
#
####################################################################


[crowsnest]
log_path: /home/stephanevdb/printer_data/logs/crowsnest.log
log_level: verbose
delete_log: false
no_proxy: false


#####################################################################
#   Top-Down Camera (Print monitoring)
#####################################################################

[cam top]
mode: camera-streamer
enable_rtsp: false
rtsp_port: 8554
port: 8080
device: /dev/v4l/by-id/usb-DSJ_UC60_Video_200901010001-video-index0
resolution: 640x480
max_fps: 15


#####################################################################
#   KTAMV Camera (Nozzle alignment)
#####################################################################

[cam ktamv]
mode: camera-streamer
enable_rtsp: false
rtsp_port: 8555
port: 8081
device: /dev/v4l/by-id/usb-046d_0825_05A5C350-video-index0
resolution: 640x480
max_fps: 5
